sudo: false
language: node_js
node_js:
- '6'
os:
- osx
- linux
before_install:
- if [ $TRAVIS_OS_NAME == "linux" ]; then export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
  sh -e /etc/init.d/xvfb start; sleep 3; fi
- npm install -g typescript@3.0.0-dev.20180626
install:
- npm install
- npm run vscode:prepublish
- npm install -g vsce
- vsce package
script:
- npm test --silent
deploy:
  provider : npm
  email : gorkem.ercan@gmail.com
  api_key:
    secure: BOtaGfNaAl0zGlsuVakvQTe45FHxxbvVaS7O1h1mVmoxr/a985UeRPF9dxxcAaAhVdCZ93OwY6f3fdP2Mn87hOPksCaBfvlTccOBxyWfnF4TaRecsAOcq+iVzZwBNEsQBD0YRESUYiMjv7uT17pkVxOJ7Id8L3FfEUcN9EUWb+AfMFw8qJjCXIT8KjfdeG2EPkJll4qvsYXbOepPJOnPchTJpkYMc8gGGlFVAAqO+RX0r3wanSuUF0oxmunOwGcrF2qKgFCGgLMAkv7r6MAGcD3iK0xVaU4xBU9XSNYSrsgap43f7LFb1lWMpxpSCxB1Vw/D4s2TeJX1CozfrM0SPhOU6B8re1iift8aUCqKee2qjaYitpE8FIha9LWdtxAfCItO96jzVOxuYcxeM94hpl5aMeUaCTTC7Bln+qS+J6Vg2eBn6k3uVvyDmtT+2dul0L/iMuIgECBtiATEWAkMo/TheiQWAAKKlFEx0e7tzBfnlW42d4t4fTVE/znMPp/fMcLF25h64I2wYsemMMPh/yN6zQRKhONlLlNFY+x+3hDyUD2FHukk4xifZfJrvjF00bGPGB3HwIGbVvIcoyWiXSzWSmycgey7ZZM8uclJ/9B1Y8Ct73C6zz1rqlgQ1tqBm07v+nNOGNJASphTEWmrdVXY3ZCHB2OnBbnD11a9NUA=
