multipass: true
plugins:
  - removeDoctype                   : false
  - removeXMLProcInst               : false
  - removeComments                  : false
  - removeMetadata                  : false
  - removeXMLNS                     : false
  - removeEditorsNSData             : false
  - cleanupAttrs                    : false
  - inlineStyles                    : false
  - minifyStyles                    : false
  - convertStyleToAttrs             : false
  - cleanupIDs                      : false
  - removeRasterImages              : false
  - removeUselessDefs               : false
  - cleanupNumericValues            : false
  - cleanupListOfValues             : false
  - convertColors                   : false
  - removeUnknownsAndDefaults       : false
  - removeNonInheritableGroupAttrs  : false
  - removeUselessStrokeAndFill      : false
  - removeViewBox                   : false
  - cleanupEnableBackground         : false
  - removeHiddenElems               : false
  - removeEmptyText                 : false
  - convertShapeToPath              : false
  - moveElemsAttrsToGroup           : false
  - moveGroupAttrsToElems           : false
  - collapseGroups                  : false
  - convertPathData                 : false
  - convertTransform                : false
  - removeEmptyAttrs                : false
  - removeEmptyContainers           : false
  - mergePaths                      : false
  - removeUnusedNS                  : false
  - transformsWithOnePath           : false
  - sortAttrs                       : true
  - removeTitle                     : false
  - removeDesc                      : false
  - removeDimensions                : false
  - removeAttrs                     : false
  - removeElementsByAttr            : false
  - addClassesToSVGElement          : false
  - removeStyleElement              : false
  - removeScriptElement             : false
  - addAttributesToSVGElement       : false
js2svg:
  pretty: true